version: "3.7"

services:
  frontend:
    container_name: metafy-vue
    build: .
    networks:
      - proxy
      - default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.metafy-secure.entrypoints=websecure"
      - "traefik.http.routers.metafy-secure.rule=Host(`metafy.omererdem.nl`)"

networks:
  proxy:
    external: true